version: '1'

services:
  identity-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: identity-service
    ports:
      - "8081:8080"
    depends_on:
      - identity-service-db

  identity-service-db:
    image: postgres
    container_name: identity-service-db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: identityservice
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:


