name: Full CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    env:
      CI: false
      DOTNET_VERSION: 8.0.x
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Setting up dotnet
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
         dotnet-version: ${{ env.DOTNET_VERSION }}
        
      - name: Build identity_service
        run: |
          cd identity_service
          dotnet restore "identity_service.sln"
          dotnet build

      - name: Analysis identity_service
        run: |
          cd identity_service
          dotnet sonarscanner begin /k:"s" /d:sonar.host.url="http://localhost:9000"  /d:sonar.login="sqp_7e41542d45d877fe2a7214b54705df71f6b33e64"
          dotnet build
          dotnet sonarscanner end /d:sonar.login="sqp_7e41542d45d877fe2a7214b54705df71f6b33e64"

        
