name: Full CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
        run: |
            cd frontend
            npm install
            npm run build --if-present
    
      # Build and run backend services
      - name: Build and run backend services
        run: |
          cd identity_service
          dotnet restore "identity_service.sln"
          dotnet build "identity_service.sln"
          
          # Repeat for other services as needed

      # Start Cypress tests
      - name: Install Cypress and run tests
        run: |
          cd tests
          npm install cypress --save-dev
          npx cypress run
