name: identity-api
on:
  push:
    branches: [ main ]
    paths:
      - identity_service/**
      - .github/workflows/identity-api.yml
  pull_request:
    branches: [ main ]
    paths:
      - identity_service/**
      - .github/workflows/identity-api.yml

  workflow_dispatch:
  
env:
  SERVICE: identity_api
  DOTNET_VERSION: 8.0.x

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout Github Action'
      uses: actions/checkout@main
    
    - name: Setup dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
        
    - name: Install Docker
      run: |
          sudo apt-get update
          sudo apt-get install -y docker.io
          sudo apt-get install -y docker-compose
    
    - name: Run docker-compose
        run: |
          docker-compose up --build
        
        
