name: Full CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CI: false
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Install dependencies and build frontend
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'
      - name: Install dependencies and build frontend
        run: |
            cd frontend
            npm install
            npm run build --if-present
    

      # Start Cypress tests
      - name: Install Cypress and run tests
        run: |
          cd frontend
          npx cypress run
