name: Full CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      # Install dependencies and build frontend
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install dependencies and build frontend
        run: |
          cd frontend
          npm install
          npm run build
      # Build and run backend services
      - name: Build and run backend services
        run: |
          cd identity_service
          dotnet restore "identity_service.sln"
          dotnet build "identity_service.sln"
          
          # Repeat for other services as needed

      # Start Cypress tests
      - name: Install Cypress and run tests
        run: |
          cd tests
          npm install cypress --save-dev
          npx cypress run
